### ISSUE TITLE
Suggestion! paradrop into wasteland?

### ISSUE THREAD

**Issue by ancientevil** [LouDnl/ArmA3_Wasteland.Altis#37]
Do you think this is implementable into a vendor or on certain places on map with perhaps 30 min to 1 hour cooldown
http://www.armaholic.com/page.php?id=21307

Or is it possible to "call" spawnbeacon paradrop script when purchasing a paradrop from a vendor or certain "place"?

**Comment by LouDnl** [comment]
I don't really like the paradrop idea. You can already place spawnbeacons which you can also set to paradrop.
